version: "3.7"
services:
  python_3_8_10:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: python_3_8_10-image
    container_name: python_3_8_10-container
    tty: true
